spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=CuatrimestreApp;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:SA}
    password: ${DB_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: false

server:
  port: 8080

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET:}
