spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://host.docker.internal:1433;databaseName=CuatrimestreApp;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:SA}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:}

server:
  port: 8080

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET:}
